package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/container/adaptive_pool.hpp",
        "include/boost/container/allocator.hpp",
        "include/boost/container/allocator_traits.hpp",
        "include/boost/container/container_fwd.hpp",
        "include/boost/container/deque.hpp",
        "include/boost/container/detail/adaptive_node_pool.hpp",
        "include/boost/container/detail/adaptive_node_pool_impl.hpp",
        "include/boost/container/detail/addressof.hpp",
        "include/boost/container/detail/advanced_insert_int.hpp",
        "include/boost/container/detail/algorithm.hpp",
        "include/boost/container/detail/alloc_helpers.hpp",
        "include/boost/container/detail/alloc_lib.h",
        "include/boost/container/detail/alloc_lib_auto_link.hpp",
        "include/boost/container/detail/allocation_type.hpp",
        "include/boost/container/detail/allocator_version_traits.hpp",
        "include/boost/container/detail/auto_link.hpp",
        "include/boost/container/detail/compare_functors.hpp",
        "include/boost/container/detail/config_begin.hpp",
        "include/boost/container/detail/config_end.hpp",
        "include/boost/container/detail/construct_in_place.hpp",
        "include/boost/container/detail/copy_move_algo.hpp",
        "include/boost/container/detail/destroyers.hpp",
        "include/boost/container/detail/flat_tree.hpp",
        "include/boost/container/detail/function_detector.hpp",
        "include/boost/container/detail/hash_table.hpp",
        "include/boost/container/detail/iterator.hpp",
        "include/boost/container/detail/iterator_to_raw_pointer.hpp",
        "include/boost/container/detail/iterators.hpp",
        "include/boost/container/detail/math_functions.hpp",
        "include/boost/container/detail/min_max.hpp",
        "include/boost/container/detail/minimal_char_traits_header.hpp",
        "include/boost/container/detail/mpl.hpp",
        "include/boost/container/detail/multiallocation_chain.hpp",
        "include/boost/container/detail/mutex.hpp",
        "include/boost/container/detail/next_capacity.hpp",
        "include/boost/container/detail/node_alloc_holder.hpp",
        "include/boost/container/detail/node_pool.hpp",
        "include/boost/container/detail/node_pool_impl.hpp",
        "include/boost/container/detail/pair.hpp",
        "include/boost/container/detail/placement_new.hpp",
        "include/boost/container/detail/pool_common.hpp",
        "include/boost/container/detail/pool_common_alloc.hpp",
        "include/boost/container/detail/singleton.hpp",
        "include/boost/container/detail/std_fwd.hpp",
        "include/boost/container/detail/to_raw_pointer.hpp",
        "include/boost/container/detail/transform_iterator.hpp",
        "include/boost/container/detail/tree.hpp",
        "include/boost/container/detail/type_traits.hpp",
        "include/boost/container/detail/value_init.hpp",
        "include/boost/container/detail/variadic_templates_tools.hpp",
        "include/boost/container/detail/version_type.hpp",
        "include/boost/container/detail/workaround.hpp",
        "include/boost/container/flat_map.hpp",
        "include/boost/container/flat_set.hpp",
        "include/boost/container/list.hpp",
        "include/boost/container/map.hpp",
        "include/boost/container/new_allocator.hpp",
        "include/boost/container/node_allocator.hpp",
        "include/boost/container/options.hpp",
        "include/boost/container/scoped_allocator.hpp",
        "include/boost/container/scoped_allocator_fwd.hpp",
        "include/boost/container/set.hpp",
        "include/boost/container/slist.hpp",
        "include/boost/container/small_vector.hpp",
        "include/boost/container/stable_vector.hpp",
        "include/boost/container/static_vector.hpp",
        "include/boost/container/string.hpp",
        "include/boost/container/throw_exception.hpp",
        "include/boost/container/vector.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "container",
    srcs = [],
    hdrs = [
        "include/boost/container/adaptive_pool.hpp",
        "include/boost/container/allocator.hpp",
        "include/boost/container/allocator_traits.hpp",
        "include/boost/container/container_fwd.hpp",
        "include/boost/container/deque.hpp",
        "include/boost/container/detail/adaptive_node_pool.hpp",
        "include/boost/container/detail/adaptive_node_pool_impl.hpp",
        "include/boost/container/detail/addressof.hpp",
        "include/boost/container/detail/advanced_insert_int.hpp",
        "include/boost/container/detail/algorithm.hpp",
        "include/boost/container/detail/alloc_helpers.hpp",
        "include/boost/container/detail/alloc_lib.h",
        "include/boost/container/detail/alloc_lib_auto_link.hpp",
        "include/boost/container/detail/allocation_type.hpp",
        "include/boost/container/detail/allocator_version_traits.hpp",
        "include/boost/container/detail/auto_link.hpp",
        "include/boost/container/detail/compare_functors.hpp",
        "include/boost/container/detail/config_begin.hpp",
        "include/boost/container/detail/config_end.hpp",
        "include/boost/container/detail/construct_in_place.hpp",
        "include/boost/container/detail/copy_move_algo.hpp",
        "include/boost/container/detail/destroyers.hpp",
        "include/boost/container/detail/flat_tree.hpp",
        "include/boost/container/detail/function_detector.hpp",
        "include/boost/container/detail/hash_table.hpp",
        "include/boost/container/detail/iterator.hpp",
        "include/boost/container/detail/iterator_to_raw_pointer.hpp",
        "include/boost/container/detail/iterators.hpp",
        "include/boost/container/detail/math_functions.hpp",
        "include/boost/container/detail/min_max.hpp",
        "include/boost/container/detail/minimal_char_traits_header.hpp",
        "include/boost/container/detail/mpl.hpp",
        "include/boost/container/detail/multiallocation_chain.hpp",
        "include/boost/container/detail/mutex.hpp",
        "include/boost/container/detail/next_capacity.hpp",
        "include/boost/container/detail/node_alloc_holder.hpp",
        "include/boost/container/detail/node_pool.hpp",
        "include/boost/container/detail/node_pool_impl.hpp",
        "include/boost/container/detail/pair.hpp",
        "include/boost/container/detail/placement_new.hpp",
        "include/boost/container/detail/pool_common.hpp",
        "include/boost/container/detail/pool_common_alloc.hpp",
        "include/boost/container/detail/singleton.hpp",
        "include/boost/container/detail/std_fwd.hpp",
        "include/boost/container/detail/to_raw_pointer.hpp",
        "include/boost/container/detail/transform_iterator.hpp",
        "include/boost/container/detail/tree.hpp",
        "include/boost/container/detail/type_traits.hpp",
        "include/boost/container/detail/value_init.hpp",
        "include/boost/container/detail/variadic_templates_tools.hpp",
        "include/boost/container/detail/version_type.hpp",
        "include/boost/container/detail/workaround.hpp",
        "include/boost/container/flat_map.hpp",
        "include/boost/container/flat_set.hpp",
        "include/boost/container/list.hpp",
        "include/boost/container/map.hpp",
        "include/boost/container/new_allocator.hpp",
        "include/boost/container/node_allocator.hpp",
        "include/boost/container/options.hpp",
        "include/boost/container/scoped_allocator.hpp",
        "include/boost/container/scoped_allocator_fwd.hpp",
        "include/boost/container/set.hpp",
        "include/boost/container/slist.hpp",
        "include/boost/container/small_vector.hpp",
        "include/boost/container/stable_vector.hpp",
        "include/boost/container/static_vector.hpp",
        "include/boost/container/string.hpp",
        "include/boost/container/throw_exception.hpp",
        "include/boost/container/vector.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/move/utility_core.hpp:
        "@boost_move//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/assert.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/intrusive/detail/minimal_less_equal_header.hpp:
        "@boost_intrusive//:headers_only",
        # Because of boost/core/no_exceptions_support.hpp:
        "@boost_core//:headers_only",
        # Because of boost/functional/hash.hpp:
        "@boost_functional//:headers_only",
        # Because of boost/type_traits/is_integral.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/integer/static_log2.hpp:
        "@boost_integer//:headers_only",
        # Because of boost/preprocessor/repetition/enum_params.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/detail/container_fwd.hpp:
        "@boost_detail//:headers_only",
        # Because of boost/mpl/aux_/lambda_support.hpp:
        "@boost_mpl//:headers_only",
    ],
)
