package(visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/convert.hpp",
        "include/boost/convert/base.hpp",
        "include/boost/convert/detail/boost_parameter_ext.hpp",
        "include/boost/convert/detail/char.hpp",
        "include/boost/convert/detail/forward.hpp",
        "include/boost/convert/detail/has_member.hpp",
        "include/boost/convert/detail/is_callable.hpp",
        "include/boost/convert/detail/is_converter.hpp",
        "include/boost/convert/detail/is_fun.hpp",
        "include/boost/convert/detail/is_string.hpp",
        "include/boost/convert/detail/range.hpp",
        "include/boost/convert/lexical_cast.hpp",
        "include/boost/convert/parameters.hpp",
        "include/boost/convert/printf.hpp",
        "include/boost/convert/spirit.hpp",
        "include/boost/convert/stream.hpp",
        "include/boost/convert/strtol.hpp",
        "include/boost/make_default.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "convert",
    srcs = [],
    hdrs = [
        "include/boost/convert.hpp",
        "include/boost/convert/base.hpp",
        "include/boost/convert/detail/boost_parameter_ext.hpp",
        "include/boost/convert/detail/char.hpp",
        "include/boost/convert/detail/forward.hpp",
        "include/boost/convert/detail/has_member.hpp",
        "include/boost/convert/detail/is_callable.hpp",
        "include/boost/convert/detail/is_converter.hpp",
        "include/boost/convert/detail/is_fun.hpp",
        "include/boost/convert/detail/is_string.hpp",
        "include/boost/convert/detail/range.hpp",
        "include/boost/convert/lexical_cast.hpp",
        "include/boost/convert/parameters.hpp",
        "include/boost/convert/printf.hpp",
        "include/boost/convert/spirit.hpp",
        "include/boost/convert/stream.hpp",
        "include/boost/convert/strtol.hpp",
        "include/boost/make_default.hpp",
    ],
    copts = [],
    visibility = ["//visibility:public"],
    deps = [
        ":@boost_accumulators//:accumulators",
        ":@boost_algorithm//:algorithm",
        ":@boost_align//:align",
        ":@boost_array//:array",
        ":@boost_assert//:assert",
        ":@boost_atomic//:atomic",
        ":@boost_bind//:bind",
        ":@boost_chrono//:chrono",
        ":@boost_circular_buffer//:circular_buffer",
        ":@boost_concept_check//:concept_check",
        ":@boost_config//:config",
        ":@boost_container//:container",
        ":@boost_conversion//:conversion",
        ":@boost_core//:core",
        ":@boost_date_time//:date_time",
        ":@boost_detail//:detail",
        ":@boost_exception//:exception",
        ":@boost_filesystem//:filesystem",
        ":@boost_foreach//:foreach",
        ":@boost_format//:format",
        ":@boost_function//:function",
        ":@boost_function_types//:function_types",
        ":@boost_functional//:functional",
        ":@boost_fusion//:fusion",
        ":@boost_integer//:integer",
        ":@boost_intrusive//:intrusive",
        ":@boost_io//:io",
        ":@boost_iostreams//:iostreams",
        ":@boost_iterator//:iterator",
        ":@boost_lexical_cast//:lexical_cast",
        ":@boost_math//:math",
        ":@boost_move//:move",
        ":@boost_mpl//:mpl",
        ":@boost_optional//:optional",
        ":@boost_parameter//:parameter",
        ":@boost_phoenix//:phoenix",
        ":@boost_pool//:pool",
        ":@boost_predef//:predef",
        ":@boost_preprocessor//:preprocessor",
        ":@boost_proto//:proto",
        ":@boost_python//:python",
        ":@boost_random//:random",
        ":@boost_range//:range",
        ":@boost_ratio//:ratio",
        ":@boost_rational//:rational",
        ":@boost_regex//:regex",
        ":@boost_serialization//:serialization",
        ":@boost_smart_ptr//:smart_ptr",
        ":@boost_spirit//:spirit",
        ":@boost_static_assert//:static_assert",
        ":@boost_system//:system",
        ":@boost_thread//:thread",
        ":@boost_throw_exception//:throw_exception",
        ":@boost_tokenizer//:tokenizer",
        ":@boost_tuple//:tuple",
        ":@boost_type_index//:type_index",
        ":@boost_type_traits//:type_traits",
        ":@boost_typeof//:typeof",
        ":@boost_unordered//:unordered",
        ":@boost_utility//:utility",
        ":@boost_variant//:variant",
        ":@boost_winapi//:winapi",
        ":convert_hdrs",
    ],
)
