package(visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/coroutine2/all.hpp",
        "include/boost/coroutine2/coroutine.hpp",
        "include/boost/coroutine2/detail/config.hpp",
        "include/boost/coroutine2/detail/coroutine.hpp",
        "include/boost/coroutine2/detail/decay_copy.hpp",
        "include/boost/coroutine2/detail/disable_overload.hpp",
        "include/boost/coroutine2/detail/forced_unwind.hpp",
        "include/boost/coroutine2/detail/pull_control_block_cc.hpp",
        "include/boost/coroutine2/detail/pull_control_block_ecv1.hpp",
        "include/boost/coroutine2/detail/pull_coroutine.hpp",
        "include/boost/coroutine2/detail/push_control_block_cc.hpp",
        "include/boost/coroutine2/detail/push_control_block_ecv1.hpp",
        "include/boost/coroutine2/detail/push_coroutine.hpp",
        "include/boost/coroutine2/detail/state.hpp",
        "include/boost/coroutine2/detail/wrap.hpp",
        "include/boost/coroutine2/fixedsize_stack.hpp",
        "include/boost/coroutine2/pooled_fixedsize_stack.hpp",
        "include/boost/coroutine2/protected_fixedsize_stack.hpp",
        "include/boost/coroutine2/segmented_stack.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "coroutine2",
    srcs = [],
    hdrs = [
        "include/boost/coroutine2/all.hpp",
        "include/boost/coroutine2/coroutine.hpp",
        "include/boost/coroutine2/detail/config.hpp",
        "include/boost/coroutine2/detail/coroutine.hpp",
        "include/boost/coroutine2/detail/decay_copy.hpp",
        "include/boost/coroutine2/detail/disable_overload.hpp",
        "include/boost/coroutine2/detail/forced_unwind.hpp",
        "include/boost/coroutine2/detail/pull_control_block_cc.hpp",
        "include/boost/coroutine2/detail/pull_control_block_ecv1.hpp",
        "include/boost/coroutine2/detail/pull_coroutine.hpp",
        "include/boost/coroutine2/detail/push_control_block_cc.hpp",
        "include/boost/coroutine2/detail/push_control_block_ecv1.hpp",
        "include/boost/coroutine2/detail/push_coroutine.hpp",
        "include/boost/coroutine2/detail/state.hpp",
        "include/boost/coroutine2/detail/wrap.hpp",
        "include/boost/coroutine2/fixedsize_stack.hpp",
        "include/boost/coroutine2/pooled_fixedsize_stack.hpp",
        "include/boost/coroutine2/protected_fixedsize_stack.hpp",
        "include/boost/coroutine2/segmented_stack.hpp",
    ],
    copts = [],
    visibility = ["//visibility:public"],
    deps = [
        ":@boost_align//:align",
        ":@boost_assert//:assert",
        ":@boost_bind//:bind",
        ":@boost_concept_check//:concept_check",
        ":@boost_config//:config",
        ":@boost_context//:context",
        ":@boost_conversion//:conversion",
        ":@boost_core//:core",
        ":@boost_detail//:detail",
        ":@boost_fiber//:fiber",
        ":@boost_function//:function",
        ":@boost_function_types//:function_types",
        ":@boost_functional//:functional",
        ":@boost_integer//:integer",
        ":@boost_intrusive//:intrusive",
        ":@boost_iterator//:iterator",
        ":@boost_move//:move",
        ":@boost_mpl//:mpl",
        ":@boost_optional//:optional",
        ":@boost_preprocessor//:preprocessor",
        ":@boost_smart_ptr//:smart_ptr",
        ":@boost_static_assert//:static_assert",
        ":@boost_throw_exception//:throw_exception",
        ":@boost_tuple//:tuple",
        ":@boost_type_traits//:type_traits",
        ":@boost_typeof//:typeof",
        ":@boost_utility//:utility",
        ":coroutine2_hdrs",
    ],
)
