package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/date_time.hpp",
        "include/boost/date_time/adjust_functors.hpp",
        "include/boost/date_time/c_local_time_adjustor.hpp",
        "include/boost/date_time/c_time.hpp",
        "include/boost/date_time/compiler_config.hpp",
        "include/boost/date_time/constrained_value.hpp",
        "include/boost/date_time/date.hpp",
        "include/boost/date_time/date_clock_device.hpp",
        "include/boost/date_time/date_defs.hpp",
        "include/boost/date_time/date_duration.hpp",
        "include/boost/date_time/date_duration_types.hpp",
        "include/boost/date_time/date_facet.hpp",
        "include/boost/date_time/date_format_simple.hpp",
        "include/boost/date_time/date_formatting.hpp",
        "include/boost/date_time/date_formatting_limited.hpp",
        "include/boost/date_time/date_formatting_locales.hpp",
        "include/boost/date_time/date_generator_formatter.hpp",
        "include/boost/date_time/date_generator_parser.hpp",
        "include/boost/date_time/date_generators.hpp",
        "include/boost/date_time/date_iterator.hpp",
        "include/boost/date_time/date_names_put.hpp",
        "include/boost/date_time/date_parsing.hpp",
        "include/boost/date_time/dst_rules.hpp",
        "include/boost/date_time/dst_transition_generators.hpp",
        "include/boost/date_time/filetime_functions.hpp",
        "include/boost/date_time/format_date_parser.hpp",
        "include/boost/date_time/gregorian/conversion.hpp",
        "include/boost/date_time/gregorian/formatters.hpp",
        "include/boost/date_time/gregorian/formatters_limited.hpp",
        "include/boost/date_time/gregorian/greg_calendar.hpp",
        "include/boost/date_time/gregorian/greg_date.hpp",
        "include/boost/date_time/gregorian/greg_day.hpp",
        "include/boost/date_time/gregorian/greg_day_of_year.hpp",
        "include/boost/date_time/gregorian/greg_duration.hpp",
        "include/boost/date_time/gregorian/greg_duration_types.hpp",
        "include/boost/date_time/gregorian/greg_facet.hpp",
        "include/boost/date_time/gregorian/greg_month.hpp",
        "include/boost/date_time/gregorian/greg_serialize.hpp",
        "include/boost/date_time/gregorian/greg_weekday.hpp",
        "include/boost/date_time/gregorian/greg_year.hpp",
        "include/boost/date_time/gregorian/greg_ymd.hpp",
        "include/boost/date_time/gregorian/gregorian.hpp",
        "include/boost/date_time/gregorian/gregorian_io.hpp",
        "include/boost/date_time/gregorian/gregorian_types.hpp",
        "include/boost/date_time/gregorian/parsers.hpp",
        "include/boost/date_time/gregorian_calendar.hpp",
        "include/boost/date_time/gregorian_calendar.ipp",
        "include/boost/date_time/int_adapter.hpp",
        "include/boost/date_time/iso_format.hpp",
        "include/boost/date_time/local_time/conversion.hpp",
        "include/boost/date_time/local_time/custom_time_zone.hpp",
        "include/boost/date_time/local_time/date_duration_operators.hpp",
        "include/boost/date_time/local_time/dst_transition_day_rules.hpp",
        "include/boost/date_time/local_time/local_date_time.hpp",
        "include/boost/date_time/local_time/local_time.hpp",
        "include/boost/date_time/local_time/local_time_io.hpp",
        "include/boost/date_time/local_time/local_time_types.hpp",
        "include/boost/date_time/local_time/posix_time_zone.hpp",
        "include/boost/date_time/local_time/tz_database.hpp",
        "include/boost/date_time/local_time_adjustor.hpp",
        "include/boost/date_time/local_timezone_defs.hpp",
        "include/boost/date_time/locale_config.hpp",
        "include/boost/date_time/microsec_time_clock.hpp",
        "include/boost/date_time/parse_format_base.hpp",
        "include/boost/date_time/period.hpp",
        "include/boost/date_time/period_formatter.hpp",
        "include/boost/date_time/period_parser.hpp",
        "include/boost/date_time/posix_time/conversion.hpp",
        "include/boost/date_time/posix_time/date_duration_operators.hpp",
        "include/boost/date_time/posix_time/posix_time.hpp",
        "include/boost/date_time/posix_time/posix_time_config.hpp",
        "include/boost/date_time/posix_time/posix_time_duration.hpp",
        "include/boost/date_time/posix_time/posix_time_io.hpp",
        "include/boost/date_time/posix_time/posix_time_legacy_io.hpp",
        "include/boost/date_time/posix_time/posix_time_system.hpp",
        "include/boost/date_time/posix_time/posix_time_types.hpp",
        "include/boost/date_time/posix_time/ptime.hpp",
        "include/boost/date_time/posix_time/time_formatters.hpp",
        "include/boost/date_time/posix_time/time_formatters_limited.hpp",
        "include/boost/date_time/posix_time/time_parsers.hpp",
        "include/boost/date_time/posix_time/time_period.hpp",
        "include/boost/date_time/posix_time/time_serialize.hpp",
        "include/boost/date_time/special_defs.hpp",
        "include/boost/date_time/special_values_formatter.hpp",
        "include/boost/date_time/special_values_parser.hpp",
        "include/boost/date_time/string_convert.hpp",
        "include/boost/date_time/string_parse_tree.hpp",
        "include/boost/date_time/strings_from_facet.hpp",
        "include/boost/date_time/time.hpp",
        "include/boost/date_time/time_clock.hpp",
        "include/boost/date_time/time_defs.hpp",
        "include/boost/date_time/time_duration.hpp",
        "include/boost/date_time/time_facet.hpp",
        "include/boost/date_time/time_formatting_streams.hpp",
        "include/boost/date_time/time_iterator.hpp",
        "include/boost/date_time/time_parsing.hpp",
        "include/boost/date_time/time_resolution_traits.hpp",
        "include/boost/date_time/time_system_counted.hpp",
        "include/boost/date_time/time_system_split.hpp",
        "include/boost/date_time/time_zone_base.hpp",
        "include/boost/date_time/time_zone_names.hpp",
        "include/boost/date_time/tz_db_base.hpp",
        "include/boost/date_time/wrapping_int.hpp",
        "include/boost/date_time/year_month_day.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "date_time",
    srcs = [
        "src/gregorian/date_generators.cpp",
        "src/gregorian/greg_month.cpp",
        "src/gregorian/greg_names.hpp",
        "src/gregorian/greg_weekday.cpp",
        "src/gregorian/gregorian_types.cpp",
        "src/posix_time/posix_time_types.cpp",
    ],
    hdrs = [
        "include/boost/date_time.hpp",
        "include/boost/date_time/adjust_functors.hpp",
        "include/boost/date_time/c_local_time_adjustor.hpp",
        "include/boost/date_time/c_time.hpp",
        "include/boost/date_time/compiler_config.hpp",
        "include/boost/date_time/constrained_value.hpp",
        "include/boost/date_time/date.hpp",
        "include/boost/date_time/date_clock_device.hpp",
        "include/boost/date_time/date_defs.hpp",
        "include/boost/date_time/date_duration.hpp",
        "include/boost/date_time/date_duration_types.hpp",
        "include/boost/date_time/date_facet.hpp",
        "include/boost/date_time/date_format_simple.hpp",
        "include/boost/date_time/date_formatting.hpp",
        "include/boost/date_time/date_formatting_limited.hpp",
        "include/boost/date_time/date_formatting_locales.hpp",
        "include/boost/date_time/date_generator_formatter.hpp",
        "include/boost/date_time/date_generator_parser.hpp",
        "include/boost/date_time/date_generators.hpp",
        "include/boost/date_time/date_iterator.hpp",
        "include/boost/date_time/date_names_put.hpp",
        "include/boost/date_time/date_parsing.hpp",
        "include/boost/date_time/dst_rules.hpp",
        "include/boost/date_time/dst_transition_generators.hpp",
        "include/boost/date_time/filetime_functions.hpp",
        "include/boost/date_time/format_date_parser.hpp",
        "include/boost/date_time/gregorian/conversion.hpp",
        "include/boost/date_time/gregorian/formatters.hpp",
        "include/boost/date_time/gregorian/formatters_limited.hpp",
        "include/boost/date_time/gregorian/greg_calendar.hpp",
        "include/boost/date_time/gregorian/greg_date.hpp",
        "include/boost/date_time/gregorian/greg_day.hpp",
        "include/boost/date_time/gregorian/greg_day_of_year.hpp",
        "include/boost/date_time/gregorian/greg_duration.hpp",
        "include/boost/date_time/gregorian/greg_duration_types.hpp",
        "include/boost/date_time/gregorian/greg_facet.hpp",
        "include/boost/date_time/gregorian/greg_month.hpp",
        "include/boost/date_time/gregorian/greg_serialize.hpp",
        "include/boost/date_time/gregorian/greg_weekday.hpp",
        "include/boost/date_time/gregorian/greg_year.hpp",
        "include/boost/date_time/gregorian/greg_ymd.hpp",
        "include/boost/date_time/gregorian/gregorian.hpp",
        "include/boost/date_time/gregorian/gregorian_io.hpp",
        "include/boost/date_time/gregorian/gregorian_types.hpp",
        "include/boost/date_time/gregorian/parsers.hpp",
        "include/boost/date_time/gregorian_calendar.hpp",
        "include/boost/date_time/gregorian_calendar.ipp",
        "include/boost/date_time/int_adapter.hpp",
        "include/boost/date_time/iso_format.hpp",
        "include/boost/date_time/local_time/conversion.hpp",
        "include/boost/date_time/local_time/custom_time_zone.hpp",
        "include/boost/date_time/local_time/date_duration_operators.hpp",
        "include/boost/date_time/local_time/dst_transition_day_rules.hpp",
        "include/boost/date_time/local_time/local_date_time.hpp",
        "include/boost/date_time/local_time/local_time.hpp",
        "include/boost/date_time/local_time/local_time_io.hpp",
        "include/boost/date_time/local_time/local_time_types.hpp",
        "include/boost/date_time/local_time/posix_time_zone.hpp",
        "include/boost/date_time/local_time/tz_database.hpp",
        "include/boost/date_time/local_time_adjustor.hpp",
        "include/boost/date_time/local_timezone_defs.hpp",
        "include/boost/date_time/locale_config.hpp",
        "include/boost/date_time/microsec_time_clock.hpp",
        "include/boost/date_time/parse_format_base.hpp",
        "include/boost/date_time/period.hpp",
        "include/boost/date_time/period_formatter.hpp",
        "include/boost/date_time/period_parser.hpp",
        "include/boost/date_time/posix_time/conversion.hpp",
        "include/boost/date_time/posix_time/date_duration_operators.hpp",
        "include/boost/date_time/posix_time/posix_time.hpp",
        "include/boost/date_time/posix_time/posix_time_config.hpp",
        "include/boost/date_time/posix_time/posix_time_duration.hpp",
        "include/boost/date_time/posix_time/posix_time_io.hpp",
        "include/boost/date_time/posix_time/posix_time_legacy_io.hpp",
        "include/boost/date_time/posix_time/posix_time_system.hpp",
        "include/boost/date_time/posix_time/posix_time_types.hpp",
        "include/boost/date_time/posix_time/ptime.hpp",
        "include/boost/date_time/posix_time/time_formatters.hpp",
        "include/boost/date_time/posix_time/time_formatters_limited.hpp",
        "include/boost/date_time/posix_time/time_parsers.hpp",
        "include/boost/date_time/posix_time/time_period.hpp",
        "include/boost/date_time/posix_time/time_serialize.hpp",
        "include/boost/date_time/special_defs.hpp",
        "include/boost/date_time/special_values_formatter.hpp",
        "include/boost/date_time/special_values_parser.hpp",
        "include/boost/date_time/string_convert.hpp",
        "include/boost/date_time/string_parse_tree.hpp",
        "include/boost/date_time/strings_from_facet.hpp",
        "include/boost/date_time/time.hpp",
        "include/boost/date_time/time_clock.hpp",
        "include/boost/date_time/time_defs.hpp",
        "include/boost/date_time/time_duration.hpp",
        "include/boost/date_time/time_facet.hpp",
        "include/boost/date_time/time_formatting_streams.hpp",
        "include/boost/date_time/time_iterator.hpp",
        "include/boost/date_time/time_parsing.hpp",
        "include/boost/date_time/time_resolution_traits.hpp",
        "include/boost/date_time/time_system_counted.hpp",
        "include/boost/date_time/time_system_split.hpp",
        "include/boost/date_time/time_zone_base.hpp",
        "include/boost/date_time/time_zone_names.hpp",
        "include/boost/date_time/tz_db_base.hpp",
        "include/boost/date_time/wrapping_int.hpp",
        "include/boost/date_time/year_month_day.hpp",
    ],
    copts = [
        "-I./src",
    ],
    deps = [
        ":headers_only",
        # Because of boost/io/ios_state.hpp:
        "@boost_io//:headers_only",
        # Because of boost/throw_exception.hpp:
        "@boost_throw_exception//:headers_only",
        # Because of boost/lexical_cast.hpp:
        "@boost_lexical_cast//:headers_only",
        # Because of boost/tokenizer.hpp:
        "@boost_tokenizer//:headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/shared_ptr.hpp:
        "@boost_smart_ptr//:headers_only",
        # Because of boost/current_function.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/operators.hpp:
        "@boost_utility//:headers_only",
        # Because of boost/mpl/if.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/type_traits/is_base_of.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/range/iterator_range_core.hpp:
        "@boost_range//:headers_only",
        # Because of boost/core/addressof.hpp:
        "@boost_core//:headers_only",
        # Because of boost/container/container_fwd.hpp:
        "@boost_container//:headers_only",
        # Because of boost/iterator/iterator_facade.hpp:
        "@boost_iterator//:headers_only",
        # Because of boost/preprocessor/list/for_each_i.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/array.hpp:
        "@boost_array//:headers_only",
        # Because of boost/numeric/conversion/cast.hpp:
        "@boost_numeric_conversion//:headers_only",
        # Because of boost/integer_traits.hpp:
        "@boost_integer//:headers_only",
        # Because of boost/move/detail/std_ns_end.hpp:
        "@boost_move//:headers_only",
        # Because of boost/detail/indirect_traits.hpp:
        "@boost_detail//:headers_only",
        # Because of boost/concept_check.hpp:
        "@boost_concept_check//:headers_only",
        # Because of boost/math/special_functions/fpclassify.hpp:
        "@boost_math//:headers_only",
        # Because of boost/predef.h:
        "@boost_predef//:headers_only",
        # Because of boost/serialization/split_free.hpp:
        "@boost_serialization//:headers_only",
        # Because of boost/algorithm/string.hpp:
        "@boost_algorithm//:headers_only",
        # Because of boost/function.hpp:
        "@boost_function//:headers_only",
        # Because of boost/mem_fn.hpp:
        "@boost_bind//:headers_only",
        # Because of boost/type_index.hpp:
        "@boost_type_index//:headers_only",
        # Because of boost/container_hash/hash.hpp:
        "@boost_container_hash//:headers_only",
    ],
)
