package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/function_types/components.hpp",
        "include/boost/function_types/config/cc_names.hpp",
        "include/boost/function_types/config/compiler.hpp",
        "include/boost/function_types/config/config.hpp",
        "include/boost/function_types/detail/class_transform.hpp",
        "include/boost/function_types/detail/classifier.hpp",
        "include/boost/function_types/detail/classifier_impl/arity10_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity10_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity20_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity20_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity30_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity30_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity40_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity40_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity50_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity50_1.hpp",
        "include/boost/function_types/detail/classifier_impl/master.hpp",
        "include/boost/function_types/detail/components_as_mpl_sequence.hpp",
        "include/boost/function_types/detail/components_impl/arity10_0.hpp",
        "include/boost/function_types/detail/components_impl/arity10_1.hpp",
        "include/boost/function_types/detail/components_impl/arity20_0.hpp",
        "include/boost/function_types/detail/components_impl/arity20_1.hpp",
        "include/boost/function_types/detail/components_impl/arity30_0.hpp",
        "include/boost/function_types/detail/components_impl/arity30_1.hpp",
        "include/boost/function_types/detail/components_impl/arity40_0.hpp",
        "include/boost/function_types/detail/components_impl/arity40_1.hpp",
        "include/boost/function_types/detail/components_impl/arity50_0.hpp",
        "include/boost/function_types/detail/components_impl/arity50_1.hpp",
        "include/boost/function_types/detail/components_impl/master.hpp",
        "include/boost/function_types/detail/cv_traits.hpp",
        "include/boost/function_types/detail/encoding/aliases_def.hpp",
        "include/boost/function_types/detail/encoding/aliases_undef.hpp",
        "include/boost/function_types/detail/encoding/def.hpp",
        "include/boost/function_types/detail/encoding/undef.hpp",
        "include/boost/function_types/detail/pp_arity_loop.hpp",
        "include/boost/function_types/detail/pp_cc_loop/master.hpp",
        "include/boost/function_types/detail/pp_cc_loop/preprocessed.hpp",
        "include/boost/function_types/detail/pp_loop.hpp",
        "include/boost/function_types/detail/pp_retag_default_cc/master.hpp",
        "include/boost/function_types/detail/pp_retag_default_cc/preprocessed.hpp",
        "include/boost/function_types/detail/pp_tags/cc_tag.hpp",
        "include/boost/function_types/detail/pp_tags/master.hpp",
        "include/boost/function_types/detail/pp_tags/preprocessed.hpp",
        "include/boost/function_types/detail/pp_variate_loop/master.hpp",
        "include/boost/function_types/detail/pp_variate_loop/preprocessed.hpp",
        "include/boost/function_types/detail/retag_default_cc.hpp",
        "include/boost/function_types/detail/synthesize.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity10_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity10_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity20_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity20_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity30_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity30_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity40_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity40_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity50_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity50_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/master.hpp",
        "include/boost/function_types/detail/to_sequence.hpp",
        "include/boost/function_types/function_arity.hpp",
        "include/boost/function_types/function_pointer.hpp",
        "include/boost/function_types/function_reference.hpp",
        "include/boost/function_types/function_type.hpp",
        "include/boost/function_types/is_callable_builtin.hpp",
        "include/boost/function_types/is_function.hpp",
        "include/boost/function_types/is_function_pointer.hpp",
        "include/boost/function_types/is_function_reference.hpp",
        "include/boost/function_types/is_member_function_pointer.hpp",
        "include/boost/function_types/is_member_object_pointer.hpp",
        "include/boost/function_types/is_member_pointer.hpp",
        "include/boost/function_types/is_nonmember_callable_builtin.hpp",
        "include/boost/function_types/member_function_pointer.hpp",
        "include/boost/function_types/member_object_pointer.hpp",
        "include/boost/function_types/parameter_types.hpp",
        "include/boost/function_types/property_tags.hpp",
        "include/boost/function_types/result_type.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "function_types",
    srcs = [],
    hdrs = [
        "include/boost/function_types/components.hpp",
        "include/boost/function_types/config/cc_names.hpp",
        "include/boost/function_types/config/compiler.hpp",
        "include/boost/function_types/config/config.hpp",
        "include/boost/function_types/detail/class_transform.hpp",
        "include/boost/function_types/detail/classifier.hpp",
        "include/boost/function_types/detail/classifier_impl/arity10_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity10_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity20_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity20_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity30_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity30_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity40_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity40_1.hpp",
        "include/boost/function_types/detail/classifier_impl/arity50_0.hpp",
        "include/boost/function_types/detail/classifier_impl/arity50_1.hpp",
        "include/boost/function_types/detail/classifier_impl/master.hpp",
        "include/boost/function_types/detail/components_as_mpl_sequence.hpp",
        "include/boost/function_types/detail/components_impl/arity10_0.hpp",
        "include/boost/function_types/detail/components_impl/arity10_1.hpp",
        "include/boost/function_types/detail/components_impl/arity20_0.hpp",
        "include/boost/function_types/detail/components_impl/arity20_1.hpp",
        "include/boost/function_types/detail/components_impl/arity30_0.hpp",
        "include/boost/function_types/detail/components_impl/arity30_1.hpp",
        "include/boost/function_types/detail/components_impl/arity40_0.hpp",
        "include/boost/function_types/detail/components_impl/arity40_1.hpp",
        "include/boost/function_types/detail/components_impl/arity50_0.hpp",
        "include/boost/function_types/detail/components_impl/arity50_1.hpp",
        "include/boost/function_types/detail/components_impl/master.hpp",
        "include/boost/function_types/detail/cv_traits.hpp",
        "include/boost/function_types/detail/encoding/aliases_def.hpp",
        "include/boost/function_types/detail/encoding/aliases_undef.hpp",
        "include/boost/function_types/detail/encoding/def.hpp",
        "include/boost/function_types/detail/encoding/undef.hpp",
        "include/boost/function_types/detail/pp_arity_loop.hpp",
        "include/boost/function_types/detail/pp_cc_loop/master.hpp",
        "include/boost/function_types/detail/pp_cc_loop/preprocessed.hpp",
        "include/boost/function_types/detail/pp_loop.hpp",
        "include/boost/function_types/detail/pp_retag_default_cc/master.hpp",
        "include/boost/function_types/detail/pp_retag_default_cc/preprocessed.hpp",
        "include/boost/function_types/detail/pp_tags/cc_tag.hpp",
        "include/boost/function_types/detail/pp_tags/master.hpp",
        "include/boost/function_types/detail/pp_tags/preprocessed.hpp",
        "include/boost/function_types/detail/pp_variate_loop/master.hpp",
        "include/boost/function_types/detail/pp_variate_loop/preprocessed.hpp",
        "include/boost/function_types/detail/retag_default_cc.hpp",
        "include/boost/function_types/detail/synthesize.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity10_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity10_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity20_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity20_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity30_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity30_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity40_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity40_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity50_0.hpp",
        "include/boost/function_types/detail/synthesize_impl/arity50_1.hpp",
        "include/boost/function_types/detail/synthesize_impl/master.hpp",
        "include/boost/function_types/detail/to_sequence.hpp",
        "include/boost/function_types/function_arity.hpp",
        "include/boost/function_types/function_pointer.hpp",
        "include/boost/function_types/function_reference.hpp",
        "include/boost/function_types/function_type.hpp",
        "include/boost/function_types/is_callable_builtin.hpp",
        "include/boost/function_types/is_function.hpp",
        "include/boost/function_types/is_function_pointer.hpp",
        "include/boost/function_types/is_function_reference.hpp",
        "include/boost/function_types/is_member_function_pointer.hpp",
        "include/boost/function_types/is_member_object_pointer.hpp",
        "include/boost/function_types/is_member_pointer.hpp",
        "include/boost/function_types/is_nonmember_callable_builtin.hpp",
        "include/boost/function_types/member_function_pointer.hpp",
        "include/boost/function_types/member_object_pointer.hpp",
        "include/boost/function_types/parameter_types.hpp",
        "include/boost/function_types/property_tags.hpp",
        "include/boost/function_types/result_type.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/mpl/aux_/lambda_support.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/type_traits/remove_pointer.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/detail/workaround.hpp:
        "@boost_config//:headers_only",
        # Because of boost/type.hpp:
        "@boost_core//:headers_only",
        # Because of boost/preprocessor/slot/slot.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/blank.hpp:
        "@boost_detail//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
    ],
)
