package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/iostreams/categories.hpp",
        "include/boost/iostreams/chain.hpp",
        "include/boost/iostreams/char_traits.hpp",
        "include/boost/iostreams/checked_operations.hpp",
        "include/boost/iostreams/close.hpp",
        "include/boost/iostreams/code_converter.hpp",
        "include/boost/iostreams/combine.hpp",
        "include/boost/iostreams/compose.hpp",
        "include/boost/iostreams/concepts.hpp",
        "include/boost/iostreams/constants.hpp",
        "include/boost/iostreams/copy.hpp",
        "include/boost/iostreams/detail/absolute_path.hpp",
        "include/boost/iostreams/detail/access_control.hpp",
        "include/boost/iostreams/detail/adapter/concept_adapter.hpp",
        "include/boost/iostreams/detail/adapter/device_adapter.hpp",
        "include/boost/iostreams/detail/adapter/direct_adapter.hpp",
        "include/boost/iostreams/detail/adapter/filter_adapter.hpp",
        "include/boost/iostreams/detail/adapter/mode_adapter.hpp",
        "include/boost/iostreams/detail/adapter/non_blocking_adapter.hpp",
        "include/boost/iostreams/detail/adapter/output_iterator_adapter.hpp",
        "include/boost/iostreams/detail/adapter/range_adapter.hpp",
        "include/boost/iostreams/detail/add_facet.hpp",
        "include/boost/iostreams/detail/bool_trait_def.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/forward.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/stream.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/stream_buffer.hpp",
        "include/boost/iostreams/detail/buffer.hpp",
        "include/boost/iostreams/detail/call_traits.hpp",
        "include/boost/iostreams/detail/char_traits.hpp",
        "include/boost/iostreams/detail/codecvt_helper.hpp",
        "include/boost/iostreams/detail/codecvt_holder.hpp",
        "include/boost/iostreams/detail/config/auto_link.hpp",
        "include/boost/iostreams/detail/config/bzip2.hpp",
        "include/boost/iostreams/detail/config/codecvt.hpp",
        "include/boost/iostreams/detail/config/disable_warnings.hpp",
        "include/boost/iostreams/detail/config/dyn_link.hpp",
        "include/boost/iostreams/detail/config/enable_warnings.hpp",
        "include/boost/iostreams/detail/config/fpos.hpp",
        "include/boost/iostreams/detail/config/gcc.hpp",
        "include/boost/iostreams/detail/config/limits.hpp",
        "include/boost/iostreams/detail/config/overload_resolution.hpp",
        "include/boost/iostreams/detail/config/rtl.hpp",
        "include/boost/iostreams/detail/config/unreachable_return.hpp",
        "include/boost/iostreams/detail/config/wide_streams.hpp",
        "include/boost/iostreams/detail/config/windows_posix.hpp",
        "include/boost/iostreams/detail/config/zlib.hpp",
        "include/boost/iostreams/detail/counted_array.hpp",
        "include/boost/iostreams/detail/current_directory.hpp",
        "include/boost/iostreams/detail/default_arg.hpp",
        "include/boost/iostreams/detail/dispatch.hpp",
        "include/boost/iostreams/detail/double_object.hpp",
        "include/boost/iostreams/detail/enable_if_stream.hpp",
        "include/boost/iostreams/detail/error.hpp",
        "include/boost/iostreams/detail/execute.hpp",
        "include/boost/iostreams/detail/file_handle.hpp",
        "include/boost/iostreams/detail/forward.hpp",
        "include/boost/iostreams/detail/fstream.hpp",
        "include/boost/iostreams/detail/functional.hpp",
        "include/boost/iostreams/detail/ios.hpp",
        "include/boost/iostreams/detail/iostream.hpp",
        "include/boost/iostreams/detail/is_dereferenceable.hpp",
        "include/boost/iostreams/detail/is_iterator_range.hpp",
        "include/boost/iostreams/detail/newline.hpp",
        "include/boost/iostreams/detail/optional.hpp",
        "include/boost/iostreams/detail/param_type.hpp",
        "include/boost/iostreams/detail/path.hpp",
        "include/boost/iostreams/detail/push.hpp",
        "include/boost/iostreams/detail/push_params.hpp",
        "include/boost/iostreams/detail/resolve.hpp",
        "include/boost/iostreams/detail/restrict_impl.hpp",
        "include/boost/iostreams/detail/select.hpp",
        "include/boost/iostreams/detail/select_by_size.hpp",
        "include/boost/iostreams/detail/streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/chainbuf.hpp",
        "include/boost/iostreams/detail/streambuf/direct_streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/linked_streambuf.hpp",
        "include/boost/iostreams/detail/system_failure.hpp",
        "include/boost/iostreams/detail/template_params.hpp",
        "include/boost/iostreams/detail/translate_int_type.hpp",
        "include/boost/iostreams/detail/wrap_unwrap.hpp",
        "include/boost/iostreams/device/array.hpp",
        "include/boost/iostreams/device/back_inserter.hpp",
        "include/boost/iostreams/device/file.hpp",
        "include/boost/iostreams/device/file_descriptor.hpp",
        "include/boost/iostreams/device/mapped_file.hpp",
        "include/boost/iostreams/device/null.hpp",
        "include/boost/iostreams/filter/aggregate.hpp",
        "include/boost/iostreams/filter/bzip2.hpp",
        "include/boost/iostreams/filter/counter.hpp",
        "include/boost/iostreams/filter/grep.hpp",
        "include/boost/iostreams/filter/gzip.hpp",
        "include/boost/iostreams/filter/line.hpp",
        "include/boost/iostreams/filter/lzma.hpp",
        "include/boost/iostreams/filter/newline.hpp",
        "include/boost/iostreams/filter/regex.hpp",
        "include/boost/iostreams/filter/stdio.hpp",
        "include/boost/iostreams/filter/symmetric.hpp",
        "include/boost/iostreams/filter/test.hpp",
        "include/boost/iostreams/filter/zlib.hpp",
        "include/boost/iostreams/filter/zstd.hpp",
        "include/boost/iostreams/filtering_stream.hpp",
        "include/boost/iostreams/filtering_streambuf.hpp",
        "include/boost/iostreams/flush.hpp",
        "include/boost/iostreams/get.hpp",
        "include/boost/iostreams/imbue.hpp",
        "include/boost/iostreams/input_sequence.hpp",
        "include/boost/iostreams/invert.hpp",
        "include/boost/iostreams/operations.hpp",
        "include/boost/iostreams/operations_fwd.hpp",
        "include/boost/iostreams/optimal_buffer_size.hpp",
        "include/boost/iostreams/output_sequence.hpp",
        "include/boost/iostreams/pipeline.hpp",
        "include/boost/iostreams/positioning.hpp",
        "include/boost/iostreams/put.hpp",
        "include/boost/iostreams/putback.hpp",
        "include/boost/iostreams/read.hpp",
        "include/boost/iostreams/restrict.hpp",
        "include/boost/iostreams/seek.hpp",
        "include/boost/iostreams/skip.hpp",
        "include/boost/iostreams/slice.hpp",
        "include/boost/iostreams/stream.hpp",
        "include/boost/iostreams/stream_buffer.hpp",
        "include/boost/iostreams/tee.hpp",
        "include/boost/iostreams/traits.hpp",
        "include/boost/iostreams/traits_fwd.hpp",
        "include/boost/iostreams/write.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "iostreams",
    srcs = [
        "src/bzip2.cpp",
        "src/file_descriptor.cpp",
        "src/gzip.cpp",
        "src/lzma.cpp",
        "src/mapped_file.cpp",
        "src/zlib.cpp",
        "src/zstd.cpp",
    ],
    hdrs = [
        "include/boost/iostreams/categories.hpp",
        "include/boost/iostreams/chain.hpp",
        "include/boost/iostreams/char_traits.hpp",
        "include/boost/iostreams/checked_operations.hpp",
        "include/boost/iostreams/close.hpp",
        "include/boost/iostreams/code_converter.hpp",
        "include/boost/iostreams/combine.hpp",
        "include/boost/iostreams/compose.hpp",
        "include/boost/iostreams/concepts.hpp",
        "include/boost/iostreams/constants.hpp",
        "include/boost/iostreams/copy.hpp",
        "include/boost/iostreams/detail/absolute_path.hpp",
        "include/boost/iostreams/detail/access_control.hpp",
        "include/boost/iostreams/detail/adapter/concept_adapter.hpp",
        "include/boost/iostreams/detail/adapter/device_adapter.hpp",
        "include/boost/iostreams/detail/adapter/direct_adapter.hpp",
        "include/boost/iostreams/detail/adapter/filter_adapter.hpp",
        "include/boost/iostreams/detail/adapter/mode_adapter.hpp",
        "include/boost/iostreams/detail/adapter/non_blocking_adapter.hpp",
        "include/boost/iostreams/detail/adapter/output_iterator_adapter.hpp",
        "include/boost/iostreams/detail/adapter/range_adapter.hpp",
        "include/boost/iostreams/detail/add_facet.hpp",
        "include/boost/iostreams/detail/bool_trait_def.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/forward.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/stream.hpp",
        "include/boost/iostreams/detail/broken_overload_resolution/stream_buffer.hpp",
        "include/boost/iostreams/detail/buffer.hpp",
        "include/boost/iostreams/detail/call_traits.hpp",
        "include/boost/iostreams/detail/char_traits.hpp",
        "include/boost/iostreams/detail/codecvt_helper.hpp",
        "include/boost/iostreams/detail/codecvt_holder.hpp",
        "include/boost/iostreams/detail/config/auto_link.hpp",
        "include/boost/iostreams/detail/config/bzip2.hpp",
        "include/boost/iostreams/detail/config/codecvt.hpp",
        "include/boost/iostreams/detail/config/disable_warnings.hpp",
        "include/boost/iostreams/detail/config/dyn_link.hpp",
        "include/boost/iostreams/detail/config/enable_warnings.hpp",
        "include/boost/iostreams/detail/config/fpos.hpp",
        "include/boost/iostreams/detail/config/gcc.hpp",
        "include/boost/iostreams/detail/config/limits.hpp",
        "include/boost/iostreams/detail/config/overload_resolution.hpp",
        "include/boost/iostreams/detail/config/rtl.hpp",
        "include/boost/iostreams/detail/config/unreachable_return.hpp",
        "include/boost/iostreams/detail/config/wide_streams.hpp",
        "include/boost/iostreams/detail/config/windows_posix.hpp",
        "include/boost/iostreams/detail/config/zlib.hpp",
        "include/boost/iostreams/detail/counted_array.hpp",
        "include/boost/iostreams/detail/current_directory.hpp",
        "include/boost/iostreams/detail/default_arg.hpp",
        "include/boost/iostreams/detail/dispatch.hpp",
        "include/boost/iostreams/detail/double_object.hpp",
        "include/boost/iostreams/detail/enable_if_stream.hpp",
        "include/boost/iostreams/detail/error.hpp",
        "include/boost/iostreams/detail/execute.hpp",
        "include/boost/iostreams/detail/file_handle.hpp",
        "include/boost/iostreams/detail/forward.hpp",
        "include/boost/iostreams/detail/fstream.hpp",
        "include/boost/iostreams/detail/functional.hpp",
        "include/boost/iostreams/detail/ios.hpp",
        "include/boost/iostreams/detail/iostream.hpp",
        "include/boost/iostreams/detail/is_dereferenceable.hpp",
        "include/boost/iostreams/detail/is_iterator_range.hpp",
        "include/boost/iostreams/detail/newline.hpp",
        "include/boost/iostreams/detail/optional.hpp",
        "include/boost/iostreams/detail/param_type.hpp",
        "include/boost/iostreams/detail/path.hpp",
        "include/boost/iostreams/detail/push.hpp",
        "include/boost/iostreams/detail/push_params.hpp",
        "include/boost/iostreams/detail/resolve.hpp",
        "include/boost/iostreams/detail/restrict_impl.hpp",
        "include/boost/iostreams/detail/select.hpp",
        "include/boost/iostreams/detail/select_by_size.hpp",
        "include/boost/iostreams/detail/streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/chainbuf.hpp",
        "include/boost/iostreams/detail/streambuf/direct_streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp",
        "include/boost/iostreams/detail/streambuf/linked_streambuf.hpp",
        "include/boost/iostreams/detail/system_failure.hpp",
        "include/boost/iostreams/detail/template_params.hpp",
        "include/boost/iostreams/detail/translate_int_type.hpp",
        "include/boost/iostreams/detail/wrap_unwrap.hpp",
        "include/boost/iostreams/device/array.hpp",
        "include/boost/iostreams/device/back_inserter.hpp",
        "include/boost/iostreams/device/file.hpp",
        "include/boost/iostreams/device/file_descriptor.hpp",
        "include/boost/iostreams/device/mapped_file.hpp",
        "include/boost/iostreams/device/null.hpp",
        "include/boost/iostreams/filter/aggregate.hpp",
        "include/boost/iostreams/filter/bzip2.hpp",
        "include/boost/iostreams/filter/counter.hpp",
        "include/boost/iostreams/filter/grep.hpp",
        "include/boost/iostreams/filter/gzip.hpp",
        "include/boost/iostreams/filter/line.hpp",
        "include/boost/iostreams/filter/lzma.hpp",
        "include/boost/iostreams/filter/newline.hpp",
        "include/boost/iostreams/filter/regex.hpp",
        "include/boost/iostreams/filter/stdio.hpp",
        "include/boost/iostreams/filter/symmetric.hpp",
        "include/boost/iostreams/filter/test.hpp",
        "include/boost/iostreams/filter/zlib.hpp",
        "include/boost/iostreams/filter/zstd.hpp",
        "include/boost/iostreams/filtering_stream.hpp",
        "include/boost/iostreams/filtering_streambuf.hpp",
        "include/boost/iostreams/flush.hpp",
        "include/boost/iostreams/get.hpp",
        "include/boost/iostreams/imbue.hpp",
        "include/boost/iostreams/input_sequence.hpp",
        "include/boost/iostreams/invert.hpp",
        "include/boost/iostreams/operations.hpp",
        "include/boost/iostreams/operations_fwd.hpp",
        "include/boost/iostreams/optimal_buffer_size.hpp",
        "include/boost/iostreams/output_sequence.hpp",
        "include/boost/iostreams/pipeline.hpp",
        "include/boost/iostreams/positioning.hpp",
        "include/boost/iostreams/put.hpp",
        "include/boost/iostreams/putback.hpp",
        "include/boost/iostreams/read.hpp",
        "include/boost/iostreams/restrict.hpp",
        "include/boost/iostreams/seek.hpp",
        "include/boost/iostreams/skip.hpp",
        "include/boost/iostreams/slice.hpp",
        "include/boost/iostreams/stream.hpp",
        "include/boost/iostreams/stream_buffer.hpp",
        "include/boost/iostreams/tee.hpp",
        "include/boost/iostreams/traits.hpp",
        "include/boost/iostreams/traits_fwd.hpp",
        "include/boost/iostreams/write.hpp",
    ],
    copts = [
        "-I./src",
    ],
    deps = [
        ":headers_only",
        "@boost_throw_exception//:throw_exception",
        "@boost_config//:config",
        "@boost_numeric_conversion//:numeric_conversion",
        "@boost_integer//:integer",
        # Because of boost/integer_traits.hpp:
        "@boost_integer//:headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/throw_exception.hpp:
        "@boost_throw_exception//:headers_only",
        # Because of boost/numeric/conversion/cast.hpp:
        "@boost_numeric_conversion//:headers_only",
        # Because of boost/type_traits/is_same.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/shared_ptr.hpp:
        "@boost_smart_ptr//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/current_function.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/type.hpp:
        "@boost_core//:headers_only",
        # Because of boost/mpl/identity.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/preprocessor/iteration/local.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/range/iterator_range.hpp:
        "@boost_range//:headers_only",
        # Because of boost/iterator/iterator_traits.hpp:
        "@boost_iterator//:headers_only",
        # Because of boost/concept_check.hpp:
        "@boost_concept_check//:headers_only",
        # Because of boost/utility.hpp:
        "@boost_utility//:headers_only",
        # Because of boost/detail/indirect_traits.hpp:
        "@boost_detail//:headers_only",
        # Because of boost/predef/platform/windows_runtime.h:
        "@boost_predef//:headers_only",
        # Because of boost/regex.hpp:
        "@boost_regex//:headers_only",
        # Because of boost/function.hpp:
        "@boost_function//:headers_only",
        # Because of boost/random/uniform_smallint.hpp:
        "@boost_random//:headers_only",
        # Because of boost/bind.hpp:
        "@boost_bind//:headers_only",
        # Because of boost/container_hash/hash.hpp:
        "@boost_container_hash//:headers_only",
        # Because of boost/type_index.hpp:
        "@boost_type_index//:headers_only",
    ],
)
