package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/local_function.hpp",
        "include/boost/local_function/aux_/add_pointed_const.hpp",
        "include/boost/local_function/aux_/function.hpp",
        "include/boost/local_function/aux_/macro/code_/bind.hpp",
        "include/boost/local_function/aux_/macro/code_/functor.hpp",
        "include/boost/local_function/aux_/macro/code_/result.hpp",
        "include/boost/local_function/aux_/macro/decl.hpp",
        "include/boost/local_function/aux_/macro/name.hpp",
        "include/boost/local_function/aux_/macro/typeof.hpp",
        "include/boost/local_function/aux_/member.hpp",
        "include/boost/local_function/aux_/nobind.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/bind.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/append.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/index.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/nil.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/set_error.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate_/return_count.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate_/this_count.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_binds.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_const_binds.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_error.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_params.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_returns.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/any_bind_type.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/sign.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate_/defaults.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate_/this.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/param.hpp",
        "include/boost/local_function/aux_/symbol.hpp",
        "include/boost/local_function/config.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/auto.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/bind.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/const.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/const_bind.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/default.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/add.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/is.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/remove.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/inline.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/recursive.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/register.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/return.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/this.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/thisunderscore.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/void.hpp",
        "include/boost/local_function/detail/preprocessor/line_counter.hpp",
        "include/boost/local_function/detail/preprocessor/void_list.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "local_function",
    srcs = [],
    hdrs = [
        "include/boost/local_function.hpp",
        "include/boost/local_function/aux_/add_pointed_const.hpp",
        "include/boost/local_function/aux_/function.hpp",
        "include/boost/local_function/aux_/macro/code_/bind.hpp",
        "include/boost/local_function/aux_/macro/code_/functor.hpp",
        "include/boost/local_function/aux_/macro/code_/result.hpp",
        "include/boost/local_function/aux_/macro/decl.hpp",
        "include/boost/local_function/aux_/macro/name.hpp",
        "include/boost/local_function/aux_/macro/typeof.hpp",
        "include/boost/local_function/aux_/member.hpp",
        "include/boost/local_function/aux_/nobind.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/bind.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/append.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/index.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/nil.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/set_error.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate_/return_count.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_/validate_/this_count.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_binds.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_const_binds.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_error.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_params.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_returns.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/any_bind_type.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/sign.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate_/defaults.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/decl_sign_/validate_/this.hpp",
        "include/boost/local_function/aux_/preprocessor/traits/param.hpp",
        "include/boost/local_function/aux_/symbol.hpp",
        "include/boost/local_function/config.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/auto.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/bind.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/const.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/const_bind.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/default.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/add.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/is.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/facility/remove.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/inline.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/recursive.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/register.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/return.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/this.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/thisunderscore.hpp",
        "include/boost/local_function/detail/preprocessor/keyword/void.hpp",
        "include/boost/local_function/detail/preprocessor/line_counter.hpp",
        "include/boost/local_function/detail/preprocessor/void_list.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/preprocessor/list/for_each_i.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/scope_exit.hpp:
        "@boost_scope_exit//:headers_only",
        # Because of boost/type_traits/add_const.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/utility/identity_type.hpp:
        "@boost_utility//:headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/typeof/typeof.hpp:
        "@boost_typeof//:headers_only",
        # Because of boost/mpl/assert.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/function.hpp:
        "@boost_function//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/throw_exception.hpp:
        "@boost_throw_exception//:headers_only",
        # Because of boost/mem_fn.hpp:
        "@boost_bind//:headers_only",
        # Because of boost/current_function.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/ref.hpp:
        "@boost_core//:headers_only",
        # Because of boost/type_index.hpp:
        "@boost_type_index//:headers_only",
        # Because of boost/integer.hpp:
        "@boost_integer//:headers_only",
        # Because of boost/container_hash/hash.hpp:
        "@boost_container_hash//:headers_only",
        # Because of boost/detail/container_fwd.hpp:
        "@boost_detail//:headers_only",
    ],
)
