package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/mp11.hpp",
        "include/boost/mp11/algorithm.hpp",
        "include/boost/mp11/bind.hpp",
        "include/boost/mp11/detail/config.hpp",
        "include/boost/mp11/detail/mp_append.hpp",
        "include/boost/mp11/detail/mp_count.hpp",
        "include/boost/mp11/detail/mp_fold.hpp",
        "include/boost/mp11/detail/mp_list.hpp",
        "include/boost/mp11/detail/mp_map_find.hpp",
        "include/boost/mp11/detail/mp_min_element.hpp",
        "include/boost/mp11/detail/mp_plus.hpp",
        "include/boost/mp11/detail/mp_void.hpp",
        "include/boost/mp11/detail/mp_with_index.hpp",
        "include/boost/mp11/function.hpp",
        "include/boost/mp11/integer_sequence.hpp",
        "include/boost/mp11/integral.hpp",
        "include/boost/mp11/list.hpp",
        "include/boost/mp11/map.hpp",
        "include/boost/mp11/mpl.hpp",
        "include/boost/mp11/set.hpp",
        "include/boost/mp11/tuple.hpp",
        "include/boost/mp11/utility.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "mp11",
    srcs = [],
    hdrs = [
        "include/boost/mp11.hpp",
        "include/boost/mp11/algorithm.hpp",
        "include/boost/mp11/bind.hpp",
        "include/boost/mp11/detail/config.hpp",
        "include/boost/mp11/detail/mp_append.hpp",
        "include/boost/mp11/detail/mp_count.hpp",
        "include/boost/mp11/detail/mp_fold.hpp",
        "include/boost/mp11/detail/mp_list.hpp",
        "include/boost/mp11/detail/mp_map_find.hpp",
        "include/boost/mp11/detail/mp_min_element.hpp",
        "include/boost/mp11/detail/mp_plus.hpp",
        "include/boost/mp11/detail/mp_void.hpp",
        "include/boost/mp11/detail/mp_with_index.hpp",
        "include/boost/mp11/function.hpp",
        "include/boost/mp11/integer_sequence.hpp",
        "include/boost/mp11/integral.hpp",
        "include/boost/mp11/list.hpp",
        "include/boost/mp11/map.hpp",
        "include/boost/mp11/mpl.hpp",
        "include/boost/mp11/set.hpp",
        "include/boost/mp11/tuple.hpp",
        "include/boost/mp11/utility.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/config/workaround.hpp:
        "@boost_config//:headers_only",
    ],
)
