package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/numeric/interval.hpp",
        "include/boost/numeric/interval/arith.hpp",
        "include/boost/numeric/interval/arith2.hpp",
        "include/boost/numeric/interval/arith3.hpp",
        "include/boost/numeric/interval/checking.hpp",
        "include/boost/numeric/interval/compare.hpp",
        "include/boost/numeric/interval/compare/certain.hpp",
        "include/boost/numeric/interval/compare/explicit.hpp",
        "include/boost/numeric/interval/compare/lexicographic.hpp",
        "include/boost/numeric/interval/compare/possible.hpp",
        "include/boost/numeric/interval/compare/set.hpp",
        "include/boost/numeric/interval/compare/tribool.hpp",
        "include/boost/numeric/interval/constants.hpp",
        "include/boost/numeric/interval/detail/alpha_rounding_control.hpp",
        "include/boost/numeric/interval/detail/bcc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/bugs.hpp",
        "include/boost/numeric/interval/detail/c99_rounding_control.hpp",
        "include/boost/numeric/interval/detail/c99sub_rounding_control.hpp",
        "include/boost/numeric/interval/detail/division.hpp",
        "include/boost/numeric/interval/detail/ia64_rounding_control.hpp",
        "include/boost/numeric/interval/detail/interval_prototype.hpp",
        "include/boost/numeric/interval/detail/msvc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/ppc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/sparc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/test_input.hpp",
        "include/boost/numeric/interval/detail/x86_rounding_control.hpp",
        "include/boost/numeric/interval/detail/x86gcc_rounding_control.hpp",
        "include/boost/numeric/interval/ext/integer.hpp",
        "include/boost/numeric/interval/ext/x86_fast_rounding_control.hpp",
        "include/boost/numeric/interval/hw_rounding.hpp",
        "include/boost/numeric/interval/interval.hpp",
        "include/boost/numeric/interval/io.hpp",
        "include/boost/numeric/interval/limits.hpp",
        "include/boost/numeric/interval/policies.hpp",
        "include/boost/numeric/interval/rounded_arith.hpp",
        "include/boost/numeric/interval/rounded_transc.hpp",
        "include/boost/numeric/interval/rounding.hpp",
        "include/boost/numeric/interval/transc.hpp",
        "include/boost/numeric/interval/utility.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "numeric_interval",
    srcs = [],
    hdrs = [
        "include/boost/numeric/interval.hpp",
        "include/boost/numeric/interval/arith.hpp",
        "include/boost/numeric/interval/arith2.hpp",
        "include/boost/numeric/interval/arith3.hpp",
        "include/boost/numeric/interval/checking.hpp",
        "include/boost/numeric/interval/compare.hpp",
        "include/boost/numeric/interval/compare/certain.hpp",
        "include/boost/numeric/interval/compare/explicit.hpp",
        "include/boost/numeric/interval/compare/lexicographic.hpp",
        "include/boost/numeric/interval/compare/possible.hpp",
        "include/boost/numeric/interval/compare/set.hpp",
        "include/boost/numeric/interval/compare/tribool.hpp",
        "include/boost/numeric/interval/constants.hpp",
        "include/boost/numeric/interval/detail/alpha_rounding_control.hpp",
        "include/boost/numeric/interval/detail/bcc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/bugs.hpp",
        "include/boost/numeric/interval/detail/c99_rounding_control.hpp",
        "include/boost/numeric/interval/detail/c99sub_rounding_control.hpp",
        "include/boost/numeric/interval/detail/division.hpp",
        "include/boost/numeric/interval/detail/ia64_rounding_control.hpp",
        "include/boost/numeric/interval/detail/interval_prototype.hpp",
        "include/boost/numeric/interval/detail/msvc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/ppc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/sparc_rounding_control.hpp",
        "include/boost/numeric/interval/detail/test_input.hpp",
        "include/boost/numeric/interval/detail/x86_rounding_control.hpp",
        "include/boost/numeric/interval/detail/x86gcc_rounding_control.hpp",
        "include/boost/numeric/interval/ext/integer.hpp",
        "include/boost/numeric/interval/ext/x86_fast_rounding_control.hpp",
        "include/boost/numeric/interval/hw_rounding.hpp",
        "include/boost/numeric/interval/interval.hpp",
        "include/boost/numeric/interval/io.hpp",
        "include/boost/numeric/interval/limits.hpp",
        "include/boost/numeric/interval/policies.hpp",
        "include/boost/numeric/interval/rounded_arith.hpp",
        "include/boost/numeric/interval/rounded_transc.hpp",
        "include/boost/numeric/interval/rounding.hpp",
        "include/boost/numeric/interval/transc.hpp",
        "include/boost/numeric/interval/utility.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/logic/tribool.hpp:
        "@boost_logic//:headers_only",
        # Because of boost/detail/fenv.hpp:
        "@boost_detail//:headers_only",
    ],
)
