package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/outcome.hpp",
        "include/boost/outcome/bad_access.hpp",
        "include/boost/outcome/basic_outcome.hpp",
        "include/boost/outcome/basic_result.hpp",
        "include/boost/outcome/boost_outcome.hpp",
        "include/boost/outcome/boost_result.hpp",
        "include/boost/outcome/config.hpp",
        "include/boost/outcome/convert.hpp",
        "include/boost/outcome/coroutine_support.hpp",
        "include/boost/outcome/detail/basic_outcome_exception_observers.hpp",
        "include/boost/outcome/detail/basic_outcome_exception_observers_impl.hpp",
        "include/boost/outcome/detail/basic_outcome_failure_observers.hpp",
        "include/boost/outcome/detail/basic_result_error_observers.hpp",
        "include/boost/outcome/detail/basic_result_final.hpp",
        "include/boost/outcome/detail/basic_result_storage.hpp",
        "include/boost/outcome/detail/basic_result_value_observers.hpp",
        "include/boost/outcome/detail/coroutine_support.ipp",
        "include/boost/outcome/detail/revision.hpp",
        "include/boost/outcome/detail/trait_std_error_code.hpp",
        "include/boost/outcome/detail/trait_std_exception.hpp",
        "include/boost/outcome/detail/value_storage.hpp",
        "include/boost/outcome/detail/version.hpp",
        "include/boost/outcome/experimental/coroutine_support.hpp",
        "include/boost/outcome/experimental/result.h",
        "include/boost/outcome/experimental/status-code/com_code.hpp",
        "include/boost/outcome/experimental/status-code/config.hpp",
        "include/boost/outcome/experimental/status-code/detail/nt_code_to_generic_code.ipp",
        "include/boost/outcome/experimental/status-code/detail/nt_code_to_win32_code.ipp",
        "include/boost/outcome/experimental/status-code/detail/win32_code_to_generic_code.ipp",
        "include/boost/outcome/experimental/status-code/error.hpp",
        "include/boost/outcome/experimental/status-code/errored_status_code.hpp",
        "include/boost/outcome/experimental/status-code/generic_code.hpp",
        "include/boost/outcome/experimental/status-code/iostream_support.hpp",
        "include/boost/outcome/experimental/status-code/nt_code.hpp",
        "include/boost/outcome/experimental/status-code/posix_code.hpp",
        "include/boost/outcome/experimental/status-code/status_code.hpp",
        "include/boost/outcome/experimental/status-code/status_code_domain.hpp",
        "include/boost/outcome/experimental/status-code/status_code_ptr.hpp",
        "include/boost/outcome/experimental/status-code/status_error.hpp",
        "include/boost/outcome/experimental/status-code/std_error_code.hpp",
        "include/boost/outcome/experimental/status-code/system_code.hpp",
        "include/boost/outcome/experimental/status-code/system_code_from_exception.hpp",
        "include/boost/outcome/experimental/status-code/system_error2.hpp",
        "include/boost/outcome/experimental/status-code/win32_code.hpp",
        "include/boost/outcome/experimental/status_outcome.hpp",
        "include/boost/outcome/experimental/status_result.hpp",
        "include/boost/outcome/iostream_support.hpp",
        "include/boost/outcome/outcome.hpp",
        "include/boost/outcome/policy/all_narrow.hpp",
        "include/boost/outcome/policy/base.hpp",
        "include/boost/outcome/policy/fail_to_compile_observers.hpp",
        "include/boost/outcome/policy/outcome_error_code_throw_as_system_error.hpp",
        "include/boost/outcome/policy/outcome_exception_ptr_rethrow.hpp",
        "include/boost/outcome/policy/result_error_code_throw_as_system_error.hpp",
        "include/boost/outcome/policy/result_exception_ptr_rethrow.hpp",
        "include/boost/outcome/policy/terminate.hpp",
        "include/boost/outcome/policy/throw_bad_result_access.hpp",
        "include/boost/outcome/result.hpp",
        "include/boost/outcome/std_outcome.hpp",
        "include/boost/outcome/std_result.hpp",
        "include/boost/outcome/success_failure.hpp",
        "include/boost/outcome/trait.hpp",
        "include/boost/outcome/try.hpp",
        "include/boost/outcome/utils.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "outcome",
    srcs = [],
    hdrs = [
        "include/boost/outcome.hpp",
        "include/boost/outcome/bad_access.hpp",
        "include/boost/outcome/basic_outcome.hpp",
        "include/boost/outcome/basic_result.hpp",
        "include/boost/outcome/boost_outcome.hpp",
        "include/boost/outcome/boost_result.hpp",
        "include/boost/outcome/config.hpp",
        "include/boost/outcome/convert.hpp",
        "include/boost/outcome/coroutine_support.hpp",
        "include/boost/outcome/detail/basic_outcome_exception_observers.hpp",
        "include/boost/outcome/detail/basic_outcome_exception_observers_impl.hpp",
        "include/boost/outcome/detail/basic_outcome_failure_observers.hpp",
        "include/boost/outcome/detail/basic_result_error_observers.hpp",
        "include/boost/outcome/detail/basic_result_final.hpp",
        "include/boost/outcome/detail/basic_result_storage.hpp",
        "include/boost/outcome/detail/basic_result_value_observers.hpp",
        "include/boost/outcome/detail/coroutine_support.ipp",
        "include/boost/outcome/detail/revision.hpp",
        "include/boost/outcome/detail/trait_std_error_code.hpp",
        "include/boost/outcome/detail/trait_std_exception.hpp",
        "include/boost/outcome/detail/value_storage.hpp",
        "include/boost/outcome/detail/version.hpp",
        "include/boost/outcome/experimental/coroutine_support.hpp",
        "include/boost/outcome/experimental/result.h",
        "include/boost/outcome/experimental/status-code/com_code.hpp",
        "include/boost/outcome/experimental/status-code/config.hpp",
        "include/boost/outcome/experimental/status-code/detail/nt_code_to_generic_code.ipp",
        "include/boost/outcome/experimental/status-code/detail/nt_code_to_win32_code.ipp",
        "include/boost/outcome/experimental/status-code/detail/win32_code_to_generic_code.ipp",
        "include/boost/outcome/experimental/status-code/error.hpp",
        "include/boost/outcome/experimental/status-code/errored_status_code.hpp",
        "include/boost/outcome/experimental/status-code/generic_code.hpp",
        "include/boost/outcome/experimental/status-code/iostream_support.hpp",
        "include/boost/outcome/experimental/status-code/nt_code.hpp",
        "include/boost/outcome/experimental/status-code/posix_code.hpp",
        "include/boost/outcome/experimental/status-code/status_code.hpp",
        "include/boost/outcome/experimental/status-code/status_code_domain.hpp",
        "include/boost/outcome/experimental/status-code/status_code_ptr.hpp",
        "include/boost/outcome/experimental/status-code/status_error.hpp",
        "include/boost/outcome/experimental/status-code/std_error_code.hpp",
        "include/boost/outcome/experimental/status-code/system_code.hpp",
        "include/boost/outcome/experimental/status-code/system_code_from_exception.hpp",
        "include/boost/outcome/experimental/status-code/system_error2.hpp",
        "include/boost/outcome/experimental/status-code/win32_code.hpp",
        "include/boost/outcome/experimental/status_outcome.hpp",
        "include/boost/outcome/experimental/status_result.hpp",
        "include/boost/outcome/iostream_support.hpp",
        "include/boost/outcome/outcome.hpp",
        "include/boost/outcome/policy/all_narrow.hpp",
        "include/boost/outcome/policy/base.hpp",
        "include/boost/outcome/policy/fail_to_compile_observers.hpp",
        "include/boost/outcome/policy/outcome_error_code_throw_as_system_error.hpp",
        "include/boost/outcome/policy/outcome_exception_ptr_rethrow.hpp",
        "include/boost/outcome/policy/result_error_code_throw_as_system_error.hpp",
        "include/boost/outcome/policy/result_exception_ptr_rethrow.hpp",
        "include/boost/outcome/policy/terminate.hpp",
        "include/boost/outcome/policy/throw_bad_result_access.hpp",
        "include/boost/outcome/result.hpp",
        "include/boost/outcome/std_outcome.hpp",
        "include/boost/outcome/std_result.hpp",
        "include/boost/outcome/success_failure.hpp",
        "include/boost/outcome/trait.hpp",
        "include/boost/outcome/try.hpp",
        "include/boost/outcome/utils.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/throw_exception.hpp:
        "@boost_throw_exception//:headers_only",
        # Because of boost/exception_ptr.hpp:
        "@boost_exception//:headers_only",
        # Because of boost/system/system_error.hpp:
        "@boost_system//:headers_only",
        # Because of boost/current_function.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/shared_ptr.hpp:
        "@boost_smart_ptr//:headers_only",
        # Because of boost/core/demangle.hpp:
        "@boost_core//:headers_only",
        # Because of boost/type_traits/is_nothrow_move_constructible.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/predef/platform/windows_runtime.h:
        "@boost_predef//:headers_only",
    ],
)
