package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/polygon/detail/boolean_op.hpp",
        "include/boost/polygon/detail/boolean_op_45.hpp",
        "include/boost/polygon/detail/iterator_compact_to_points.hpp",
        "include/boost/polygon/detail/iterator_geometry_to_set.hpp",
        "include/boost/polygon/detail/iterator_points_to_compact.hpp",
        "include/boost/polygon/detail/max_cover.hpp",
        "include/boost/polygon/detail/minkowski.hpp",
        "include/boost/polygon/detail/polygon_45_formation.hpp",
        "include/boost/polygon/detail/polygon_45_set_view.hpp",
        "include/boost/polygon/detail/polygon_45_touch.hpp",
        "include/boost/polygon/detail/polygon_90_set_view.hpp",
        "include/boost/polygon/detail/polygon_90_touch.hpp",
        "include/boost/polygon/detail/polygon_arbitrary_formation.hpp",
        "include/boost/polygon/detail/polygon_formation.hpp",
        "include/boost/polygon/detail/polygon_set_view.hpp",
        "include/boost/polygon/detail/polygon_simplify.hpp",
        "include/boost/polygon/detail/polygon_sort_adaptor.hpp",
        "include/boost/polygon/detail/property_merge.hpp",
        "include/boost/polygon/detail/property_merge_45.hpp",
        "include/boost/polygon/detail/rectangle_formation.hpp",
        "include/boost/polygon/detail/scan_arbitrary.hpp",
        "include/boost/polygon/detail/voronoi_ctypes.hpp",
        "include/boost/polygon/detail/voronoi_predicates.hpp",
        "include/boost/polygon/detail/voronoi_robust_fpt.hpp",
        "include/boost/polygon/detail/voronoi_structures.hpp",
        "include/boost/polygon/gmp_override.hpp",
        "include/boost/polygon/gtl.hpp",
        "include/boost/polygon/interval_concept.hpp",
        "include/boost/polygon/interval_data.hpp",
        "include/boost/polygon/interval_traits.hpp",
        "include/boost/polygon/isotropy.hpp",
        "include/boost/polygon/point_concept.hpp",
        "include/boost/polygon/point_data.hpp",
        "include/boost/polygon/point_traits.hpp",
        "include/boost/polygon/polygon.hpp",
        "include/boost/polygon/polygon_45_data.hpp",
        "include/boost/polygon/polygon_45_set_concept.hpp",
        "include/boost/polygon/polygon_45_set_data.hpp",
        "include/boost/polygon/polygon_45_set_traits.hpp",
        "include/boost/polygon/polygon_45_with_holes_data.hpp",
        "include/boost/polygon/polygon_90_data.hpp",
        "include/boost/polygon/polygon_90_set_concept.hpp",
        "include/boost/polygon/polygon_90_set_data.hpp",
        "include/boost/polygon/polygon_90_set_traits.hpp",
        "include/boost/polygon/polygon_90_with_holes_data.hpp",
        "include/boost/polygon/polygon_data.hpp",
        "include/boost/polygon/polygon_set_concept.hpp",
        "include/boost/polygon/polygon_set_data.hpp",
        "include/boost/polygon/polygon_set_traits.hpp",
        "include/boost/polygon/polygon_traits.hpp",
        "include/boost/polygon/polygon_with_holes_data.hpp",
        "include/boost/polygon/rectangle_concept.hpp",
        "include/boost/polygon/rectangle_data.hpp",
        "include/boost/polygon/rectangle_traits.hpp",
        "include/boost/polygon/segment_concept.hpp",
        "include/boost/polygon/segment_data.hpp",
        "include/boost/polygon/segment_traits.hpp",
        "include/boost/polygon/segment_utils.hpp",
        "include/boost/polygon/transform.hpp",
        "include/boost/polygon/voronoi.hpp",
        "include/boost/polygon/voronoi_builder.hpp",
        "include/boost/polygon/voronoi_diagram.hpp",
        "include/boost/polygon/voronoi_geometry_type.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "polygon",
    srcs = [],
    hdrs = [
        "include/boost/polygon/detail/boolean_op.hpp",
        "include/boost/polygon/detail/boolean_op_45.hpp",
        "include/boost/polygon/detail/iterator_compact_to_points.hpp",
        "include/boost/polygon/detail/iterator_geometry_to_set.hpp",
        "include/boost/polygon/detail/iterator_points_to_compact.hpp",
        "include/boost/polygon/detail/max_cover.hpp",
        "include/boost/polygon/detail/minkowski.hpp",
        "include/boost/polygon/detail/polygon_45_formation.hpp",
        "include/boost/polygon/detail/polygon_45_set_view.hpp",
        "include/boost/polygon/detail/polygon_45_touch.hpp",
        "include/boost/polygon/detail/polygon_90_set_view.hpp",
        "include/boost/polygon/detail/polygon_90_touch.hpp",
        "include/boost/polygon/detail/polygon_arbitrary_formation.hpp",
        "include/boost/polygon/detail/polygon_formation.hpp",
        "include/boost/polygon/detail/polygon_set_view.hpp",
        "include/boost/polygon/detail/polygon_simplify.hpp",
        "include/boost/polygon/detail/polygon_sort_adaptor.hpp",
        "include/boost/polygon/detail/property_merge.hpp",
        "include/boost/polygon/detail/property_merge_45.hpp",
        "include/boost/polygon/detail/rectangle_formation.hpp",
        "include/boost/polygon/detail/scan_arbitrary.hpp",
        "include/boost/polygon/detail/voronoi_ctypes.hpp",
        "include/boost/polygon/detail/voronoi_predicates.hpp",
        "include/boost/polygon/detail/voronoi_robust_fpt.hpp",
        "include/boost/polygon/detail/voronoi_structures.hpp",
        "include/boost/polygon/gmp_override.hpp",
        "include/boost/polygon/gtl.hpp",
        "include/boost/polygon/interval_concept.hpp",
        "include/boost/polygon/interval_data.hpp",
        "include/boost/polygon/interval_traits.hpp",
        "include/boost/polygon/isotropy.hpp",
        "include/boost/polygon/point_concept.hpp",
        "include/boost/polygon/point_data.hpp",
        "include/boost/polygon/point_traits.hpp",
        "include/boost/polygon/polygon.hpp",
        "include/boost/polygon/polygon_45_data.hpp",
        "include/boost/polygon/polygon_45_set_concept.hpp",
        "include/boost/polygon/polygon_45_set_data.hpp",
        "include/boost/polygon/polygon_45_set_traits.hpp",
        "include/boost/polygon/polygon_45_with_holes_data.hpp",
        "include/boost/polygon/polygon_90_data.hpp",
        "include/boost/polygon/polygon_90_set_concept.hpp",
        "include/boost/polygon/polygon_90_set_data.hpp",
        "include/boost/polygon/polygon_90_set_traits.hpp",
        "include/boost/polygon/polygon_90_with_holes_data.hpp",
        "include/boost/polygon/polygon_data.hpp",
        "include/boost/polygon/polygon_set_concept.hpp",
        "include/boost/polygon/polygon_set_data.hpp",
        "include/boost/polygon/polygon_set_traits.hpp",
        "include/boost/polygon/polygon_traits.hpp",
        "include/boost/polygon/polygon_with_holes_data.hpp",
        "include/boost/polygon/rectangle_concept.hpp",
        "include/boost/polygon/rectangle_data.hpp",
        "include/boost/polygon/rectangle_traits.hpp",
        "include/boost/polygon/segment_concept.hpp",
        "include/boost/polygon/segment_data.hpp",
        "include/boost/polygon/segment_traits.hpp",
        "include/boost/polygon/segment_utils.hpp",
        "include/boost/polygon/transform.hpp",
        "include/boost/polygon/voronoi.hpp",
        "include/boost/polygon/voronoi_builder.hpp",
        "include/boost/polygon/voronoi_diagram.hpp",
        "include/boost/polygon/voronoi_geometry_type.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/cstdint.hpp:
        "@boost_config//:headers_only",
        # Because of boost/mpl/protect.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/utility/enable_if.hpp:
        "@boost_core//:headers_only",
        # Because of boost/preprocessor/cat.hpp:
        "@boost_preprocessor//:headers_only",
    ],
)
