package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/sort/block_indirect_sort/blk_detail/backbone.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/block.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/constants.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/merge_blocks.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/move_blocks.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/parallel_sort.hpp",
        "include/boost/sort/block_indirect_sort/block_indirect_sort.hpp",
        "include/boost/sort/common/deque_cnc.hpp",
        "include/boost/sort/common/file_vector.hpp",
        "include/boost/sort/common/indirect.hpp",
        "include/boost/sort/common/int_array.hpp",
        "include/boost/sort/common/merge_block.hpp",
        "include/boost/sort/common/merge_four.hpp",
        "include/boost/sort/common/merge_vector.hpp",
        "include/boost/sort/common/pivot.hpp",
        "include/boost/sort/common/range.hpp",
        "include/boost/sort/common/rearrange.hpp",
        "include/boost/sort/common/scheduler.hpp",
        "include/boost/sort/common/sort_basic.hpp",
        "include/boost/sort/common/spinlock.hpp",
        "include/boost/sort/common/stack_cnc.hpp",
        "include/boost/sort/common/time_measure.hpp",
        "include/boost/sort/common/util/algorithm.hpp",
        "include/boost/sort/common/util/atomic.hpp",
        "include/boost/sort/common/util/circular_buffer.hpp",
        "include/boost/sort/common/util/insert.hpp",
        "include/boost/sort/common/util/merge.hpp",
        "include/boost/sort/common/util/search.hpp",
        "include/boost/sort/common/util/traits.hpp",
        "include/boost/sort/flat_stable_sort/flat_stable_sort.hpp",
        "include/boost/sort/heap_sort/heap_sort.hpp",
        "include/boost/sort/insert_sort/insert_sort.hpp",
        "include/boost/sort/parallel_stable_sort/parallel_stable_sort.hpp",
        "include/boost/sort/pdqsort/pdqsort.hpp",
        "include/boost/sort/sample_sort/sample_sort.hpp",
        "include/boost/sort/sort.hpp",
        "include/boost/sort/spinsort/spinsort.hpp",
        "include/boost/sort/spreadsort/detail/constants.hpp",
        "include/boost/sort/spreadsort/detail/float_sort.hpp",
        "include/boost/sort/spreadsort/detail/integer_sort.hpp",
        "include/boost/sort/spreadsort/detail/spreadsort_common.hpp",
        "include/boost/sort/spreadsort/detail/string_sort.hpp",
        "include/boost/sort/spreadsort/float_sort.hpp",
        "include/boost/sort/spreadsort/integer_sort.hpp",
        "include/boost/sort/spreadsort/spreadsort.hpp",
        "include/boost/sort/spreadsort/string_sort.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "sort",
    srcs = [],
    hdrs = [
        "include/boost/sort/block_indirect_sort/blk_detail/backbone.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/block.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/constants.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/merge_blocks.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/move_blocks.hpp",
        "include/boost/sort/block_indirect_sort/blk_detail/parallel_sort.hpp",
        "include/boost/sort/block_indirect_sort/block_indirect_sort.hpp",
        "include/boost/sort/common/deque_cnc.hpp",
        "include/boost/sort/common/file_vector.hpp",
        "include/boost/sort/common/indirect.hpp",
        "include/boost/sort/common/int_array.hpp",
        "include/boost/sort/common/merge_block.hpp",
        "include/boost/sort/common/merge_four.hpp",
        "include/boost/sort/common/merge_vector.hpp",
        "include/boost/sort/common/pivot.hpp",
        "include/boost/sort/common/range.hpp",
        "include/boost/sort/common/rearrange.hpp",
        "include/boost/sort/common/scheduler.hpp",
        "include/boost/sort/common/sort_basic.hpp",
        "include/boost/sort/common/spinlock.hpp",
        "include/boost/sort/common/stack_cnc.hpp",
        "include/boost/sort/common/time_measure.hpp",
        "include/boost/sort/common/util/algorithm.hpp",
        "include/boost/sort/common/util/atomic.hpp",
        "include/boost/sort/common/util/circular_buffer.hpp",
        "include/boost/sort/common/util/insert.hpp",
        "include/boost/sort/common/util/merge.hpp",
        "include/boost/sort/common/util/search.hpp",
        "include/boost/sort/common/util/traits.hpp",
        "include/boost/sort/flat_stable_sort/flat_stable_sort.hpp",
        "include/boost/sort/heap_sort/heap_sort.hpp",
        "include/boost/sort/insert_sort/insert_sort.hpp",
        "include/boost/sort/parallel_stable_sort/parallel_stable_sort.hpp",
        "include/boost/sort/pdqsort/pdqsort.hpp",
        "include/boost/sort/sample_sort/sample_sort.hpp",
        "include/boost/sort/sort.hpp",
        "include/boost/sort/spinsort/spinsort.hpp",
        "include/boost/sort/spreadsort/detail/constants.hpp",
        "include/boost/sort/spreadsort/detail/float_sort.hpp",
        "include/boost/sort/spreadsort/detail/integer_sort.hpp",
        "include/boost/sort/spreadsort/detail/spreadsort_common.hpp",
        "include/boost/sort/spreadsort/detail/string_sort.hpp",
        "include/boost/sort/spreadsort/float_sort.hpp",
        "include/boost/sort/spreadsort/integer_sort.hpp",
        "include/boost/sort/spreadsort/spreadsort.hpp",
        "include/boost/sort/spreadsort/string_sort.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/range/begin.hpp:
        "@boost_range//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/type_traits.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/cstdint.hpp:
        "@boost_config//:headers_only",
        # Because of boost/utility/enable_if.hpp:
        "@boost_core//:headers_only",
        # Because of boost/serialization/static_warning.hpp:
        "@boost_serialization//:headers_only",
        # Because of boost/mpl/print.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/iterator/iterator_traits.hpp:
        "@boost_iterator//:headers_only",
        # Because of boost/preprocessor/cat.hpp:
        "@boost_preprocessor//:headers_only",
    ],
)
