package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/type_erasure/any.hpp",
        "include/boost/type_erasure/any_cast.hpp",
        "include/boost/type_erasure/binding.hpp",
        "include/boost/type_erasure/binding_of.hpp",
        "include/boost/type_erasure/builtin.hpp",
        "include/boost/type_erasure/call.hpp",
        "include/boost/type_erasure/callable.hpp",
        "include/boost/type_erasure/check_match.hpp",
        "include/boost/type_erasure/concept_interface.hpp",
        "include/boost/type_erasure/concept_of.hpp",
        "include/boost/type_erasure/config.hpp",
        "include/boost/type_erasure/constructible.hpp",
        "include/boost/type_erasure/deduced.hpp",
        "include/boost/type_erasure/derived.hpp",
        "include/boost/type_erasure/detail/access.hpp",
        "include/boost/type_erasure/detail/adapt_to_vtable.hpp",
        "include/boost/type_erasure/detail/any_base.hpp",
        "include/boost/type_erasure/detail/check_call.hpp",
        "include/boost/type_erasure/detail/check_map.hpp",
        "include/boost/type_erasure/detail/const.hpp",
        "include/boost/type_erasure/detail/construct.hpp",
        "include/boost/type_erasure/detail/extract_concept.hpp",
        "include/boost/type_erasure/detail/get_placeholders.hpp",
        "include/boost/type_erasure/detail/get_signature.hpp",
        "include/boost/type_erasure/detail/instantiate.hpp",
        "include/boost/type_erasure/detail/macro.hpp",
        "include/boost/type_erasure/detail/normalize.hpp",
        "include/boost/type_erasure/detail/normalize_deduced.hpp",
        "include/boost/type_erasure/detail/null.hpp",
        "include/boost/type_erasure/detail/rebind_placeholders.hpp",
        "include/boost/type_erasure/detail/storage.hpp",
        "include/boost/type_erasure/detail/vtable.hpp",
        "include/boost/type_erasure/exception.hpp",
        "include/boost/type_erasure/free.hpp",
        "include/boost/type_erasure/is_empty.hpp",
        "include/boost/type_erasure/is_placeholder.hpp",
        "include/boost/type_erasure/is_subconcept.hpp",
        "include/boost/type_erasure/iterator.hpp",
        "include/boost/type_erasure/member.hpp",
        "include/boost/type_erasure/operators.hpp",
        "include/boost/type_erasure/param.hpp",
        "include/boost/type_erasure/placeholder.hpp",
        "include/boost/type_erasure/placeholder_of.hpp",
        "include/boost/type_erasure/rebind_any.hpp",
        "include/boost/type_erasure/relaxed.hpp",
        "include/boost/type_erasure/require_match.hpp",
        "include/boost/type_erasure/same_type.hpp",
        "include/boost/type_erasure/static_binding.hpp",
        "include/boost/type_erasure/tuple.hpp",
        "include/boost/type_erasure/typeid_of.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "type_erasure",
    srcs = [],
    hdrs = [
        "include/boost/type_erasure/any.hpp",
        "include/boost/type_erasure/any_cast.hpp",
        "include/boost/type_erasure/binding.hpp",
        "include/boost/type_erasure/binding_of.hpp",
        "include/boost/type_erasure/builtin.hpp",
        "include/boost/type_erasure/call.hpp",
        "include/boost/type_erasure/callable.hpp",
        "include/boost/type_erasure/check_match.hpp",
        "include/boost/type_erasure/concept_interface.hpp",
        "include/boost/type_erasure/concept_of.hpp",
        "include/boost/type_erasure/config.hpp",
        "include/boost/type_erasure/constructible.hpp",
        "include/boost/type_erasure/deduced.hpp",
        "include/boost/type_erasure/derived.hpp",
        "include/boost/type_erasure/detail/access.hpp",
        "include/boost/type_erasure/detail/adapt_to_vtable.hpp",
        "include/boost/type_erasure/detail/any_base.hpp",
        "include/boost/type_erasure/detail/check_call.hpp",
        "include/boost/type_erasure/detail/check_map.hpp",
        "include/boost/type_erasure/detail/const.hpp",
        "include/boost/type_erasure/detail/construct.hpp",
        "include/boost/type_erasure/detail/extract_concept.hpp",
        "include/boost/type_erasure/detail/get_placeholders.hpp",
        "include/boost/type_erasure/detail/get_signature.hpp",
        "include/boost/type_erasure/detail/instantiate.hpp",
        "include/boost/type_erasure/detail/macro.hpp",
        "include/boost/type_erasure/detail/normalize.hpp",
        "include/boost/type_erasure/detail/normalize_deduced.hpp",
        "include/boost/type_erasure/detail/null.hpp",
        "include/boost/type_erasure/detail/rebind_placeholders.hpp",
        "include/boost/type_erasure/detail/storage.hpp",
        "include/boost/type_erasure/detail/vtable.hpp",
        "include/boost/type_erasure/exception.hpp",
        "include/boost/type_erasure/free.hpp",
        "include/boost/type_erasure/is_empty.hpp",
        "include/boost/type_erasure/is_placeholder.hpp",
        "include/boost/type_erasure/is_subconcept.hpp",
        "include/boost/type_erasure/iterator.hpp",
        "include/boost/type_erasure/member.hpp",
        "include/boost/type_erasure/operators.hpp",
        "include/boost/type_erasure/param.hpp",
        "include/boost/type_erasure/placeholder.hpp",
        "include/boost/type_erasure/placeholder_of.hpp",
        "include/boost/type_erasure/rebind_any.hpp",
        "include/boost/type_erasure/relaxed.hpp",
        "include/boost/type_erasure/require_match.hpp",
        "include/boost/type_erasure/same_type.hpp",
        "include/boost/type_erasure/static_binding.hpp",
        "include/boost/type_erasure/tuple.hpp",
        "include/boost/type_erasure/typeid_of.hpp",
    ],
    copts = [],
    deps = [
        ":headers_only",
        # Because of boost/preprocessor/repetition/enum.hpp:
        "@boost_preprocessor//:headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
        # Because of boost/mpl/size.hpp:
        "@boost_mpl//:headers_only",
        # Because of boost/type_traits/remove_cv.hpp:
        "@boost_type_traits//:headers_only",
        # Because of boost/throw_exception.hpp:
        "@boost_throw_exception//:headers_only",
        # Because of boost/assert.hpp:
        "@boost_assert//:headers_only",
        # Because of boost/iterator/iterator_categories.hpp:
        "@boost_iterator//:headers_only",
        # Because of boost/utility/enable_if.hpp:
        "@boost_core//:headers_only",
        # Because of boost/fusion/include/category_of.hpp:
        "@boost_fusion//:headers_only",
        # Because of boost/make_shared.hpp:
        "@boost_smart_ptr//:headers_only",
        # Because of boost/typeof/typeof.hpp:
        "@boost_typeof//:headers_only",
        # Because of boost/static_assert.hpp:
        "@boost_static_assert//:headers_only",
        # Because of boost/align/align.hpp:
        "@boost_align//:headers_only",
        # Because of boost/predef.h:
        "@boost_predef//:headers_only",
    ],
)
