package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers_only",
    hdrs = [
        "include/boost/detail/interlocked.hpp",
        "include/boost/detail/winapi/GetCurrentProcess.hpp",
        "include/boost/detail/winapi/GetCurrentThread.hpp",
        "include/boost/detail/winapi/GetLastError.hpp",
        "include/boost/detail/winapi/GetProcessTimes.hpp",
        "include/boost/detail/winapi/GetThreadTimes.hpp",
        "include/boost/detail/winapi/LocalFree.hpp",
        "include/boost/detail/winapi/basic_types.hpp",
        "include/boost/detail/winapi/config.hpp",
        "include/boost/detail/winapi/crypt.hpp",
        "include/boost/detail/winapi/directory_management.hpp",
        "include/boost/detail/winapi/dll.hpp",
        "include/boost/detail/winapi/error_handling.hpp",
        "include/boost/detail/winapi/file_management.hpp",
        "include/boost/detail/winapi/handles.hpp",
        "include/boost/detail/winapi/memory.hpp",
        "include/boost/detail/winapi/process.hpp",
        "include/boost/detail/winapi/security.hpp",
        "include/boost/detail/winapi/synchronization.hpp",
        "include/boost/detail/winapi/system.hpp",
        "include/boost/detail/winapi/thread.hpp",
        "include/boost/detail/winapi/thread_pool.hpp",
        "include/boost/detail/winapi/time.hpp",
        "include/boost/detail/winapi/timers.hpp",
        "include/boost/detail/winapi/tls.hpp",
        "include/boost/detail/winapi/waitable_timer.hpp",
    ],
    includes = [
        "include",
    ],
)

cc_library(
    name = "winapi",
    srcs = [],
    hdrs = [
        "include/boost/detail/interlocked.hpp",
        "include/boost/detail/winapi/GetCurrentProcess.hpp",
        "include/boost/detail/winapi/GetCurrentThread.hpp",
        "include/boost/detail/winapi/GetLastError.hpp",
        "include/boost/detail/winapi/GetProcessTimes.hpp",
        "include/boost/detail/winapi/GetThreadTimes.hpp",
        "include/boost/detail/winapi/LocalFree.hpp",
        "include/boost/detail/winapi/basic_types.hpp",
        "include/boost/detail/winapi/config.hpp",
        "include/boost/detail/winapi/crypt.hpp",
        "include/boost/detail/winapi/directory_management.hpp",
        "include/boost/detail/winapi/dll.hpp",
        "include/boost/detail/winapi/error_handling.hpp",
        "include/boost/detail/winapi/file_management.hpp",
        "include/boost/detail/winapi/handles.hpp",
        "include/boost/detail/winapi/memory.hpp",
        "include/boost/detail/winapi/process.hpp",
        "include/boost/detail/winapi/security.hpp",
        "include/boost/detail/winapi/synchronization.hpp",
        "include/boost/detail/winapi/system.hpp",
        "include/boost/detail/winapi/thread.hpp",
        "include/boost/detail/winapi/thread_pool.hpp",
        "include/boost/detail/winapi/time.hpp",
        "include/boost/detail/winapi/timers.hpp",
        "include/boost/detail/winapi/tls.hpp",
        "include/boost/detail/winapi/waitable_timer.hpp",
    ],
    copts = [],
    visibility = ["//visibility:public"],
    deps = [
        ":headers_only",
        # Because of boost/config.hpp:
        "@boost_config//:headers_only",
    ],
)
